### PR TITLE
Change to Modal Pop-Up Listener

### PR DESCRIPTION
**Pull request by mokummusic**
I had a problem with the modal pop-up only opening the first time the
hash was clicked.

I have changed the modal listener from ‘AddEventListener’ to ‘jQuery
click()’.
I have also prevented the default action firing to save adding the hash
tag to the address bar.

### CODE REVIEW

**Comment by ideag** [comment]
Hi and thanks for the contribution.
I'l have to test it out, but it seems that this PR fixes one behavior, but breaks another one. The hashtag option was originally created to allow people to point from external location (say, domainA.com) to my site and directly open the modal on a different site (say, domainB.com#coffee). I'll try to reconcile both behaviors later this week.

**Comment by mokummusic** [comment]
Ahh! I wasn't aware of that requirement. ;-)

Regards
Neil

**Comment by ideag** [comment]
Not a requirement, just an use case I am pretty fond of myself :) but I think I can make it work both ways and it will be even better.

**Comment by mokummusic** [comment]
I think I have it working in both ways now. I've pushed a new commit to my fork if you want to take a look.

**Pull request closed without merging**
